commit_message: 'translation: new %language% translations from Crowdin'
append_commit_message:
pull_request_title: 'translation: New Translations'
files:
  - source: /src/locales/en.json
    translation: /src/locales/%locale%.json
